### ISSUE TITLE
Please create tag / release that includes relaxed requirements for lower oses

### ISSUE THREAD

**Issue by larryonoff** [pointfreeco/swift-identified-collections#38]

**Comment by stephencelis** [comment]
@larryonoff Can you explain more? The latest tag targets `main`.

**Comment by larryonoff** [comment]
@stephencelis the latest tag doesn't contain [commit](https://github.com/pointfreeco/swift-identified-collections/commit/2d6b7ffcc67afd9077fac5e5a29bcd6d39b71076) that relaxes platforms requirements.

Our app supports iOS 12, so these changes are needed. We tried `main` branch or revision, but Xcode reports the error.

```
Dependencies could not be resolved because root depends on 'onelight-ios-sdk' 6.53.0..<7.0.0.
'onelight-ios-sdk' >= 6.53.0 cannot be used because package 'onelight-ios-sdk' is required using a stable-version but 'onelight-ios-sdk' depends on an unstable-version package 'swift-identified-collections' and no versions of 'onelight-ios-sdk' match the requirement 6.53.1..<7.0.0.
```

**Comment by stephencelis** [comment]
Done: https://github.com/pointfreeco/swift-identified-collections/releases/tag/0.4.0

**Comment by larryonoff** [comment]
@stephencelis WOW. thanks! It was quick

**Comment by stephencelis** [comment]
@larryonoff I was very confused, ha, I checked the compare view this morning but I guess I had it configured wrong 😅
