### ISSUE TITLE
Crash when used with rearrangeable SwiftUI List

### ISSUE THREAD

**Issue by okla** [pointfreeco/swift-identified-collections#46]
I'm using `var items: IdentifiedArrayOf<MyType>` with SwiftUI's `List($items, editActions: .all)` and once I rearrange any element in the list the app crashes with `Precondition failed: Element identity must remain constant`

**Comment by okla** [comment]
Using a workaround for now
```
List {
  ForEach($items) { ... }
    .onMove {
      items.move(fromOffsets: $0, toOffset: $1)
    }
}
```

**Comment by stephencelis** [comment]
@okla Can you provide a full reproduction of the original issue you were having for us to work with? Right now we don't really have much to go off of. We do have a test for `move(fromOffsets:toOffset:)`, though:

https://github.com/pointfreeco/swift-identified-collections/blob/main/Tests/IdentifiedCollectionsTests/IdentifiedArrayTests.swift#L219

**Comment by okla** [comment]
@stephencelis Here's the full reproduction code
```swift
import SwiftUI
import IdentifiedCollections

struct Item: Identifiable {
  var id = UUID()
  var int = Int.random(in: 0...99)
}

struct ContentView: View {
  @State var items: IdentifiedArray = [Item(), Item(), Item()]

  var body: some View {
    List($items, editActions: .all) { item in
      Text("\(item.wrappedValue.int)")
    }
  }
}

@main
struct testApp: App {
  var body: some Scene {
    WindowGroup {
      ContentView()
    }
  }
}
```

**Comment by okla** [comment]
@stephencelis Works fine now!
