### ISSUE TITLE
Cut a new release to fix warnings in Xcode 14.3

### ISSUE THREAD

**Issue by scogeo** [pointfreeco/swift-identified-collections#55]
### Description

Xcode 14.3 (Swift 5.8) generates many warnings for the most recent release (0.7.0).  This has already been fixed in #54.  Could you cut a new release to incorporate the PR? 🙏

### Checklist

- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-identified-collections/issues) or [discussion](https://github.com/pointfreeco/swift-identified-collections/discussions).

### Identified Collections version information

0.7.0

### Xcode version information

14.3

### Swift Compiler version information

```shell
swift-driver version: 1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0
```

**Comment by stephencelis** [comment]
Just cut https://github.com/pointfreeco/swift-identified-collections/releases/tag/0.7.1, thanks!
